# application.yml (or application.properties)
spring:
  application:
    name: post-service
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://post-db/posts?createDatabaseIfNotExist=true
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

user:
  openapi:
    dev-url: http://localhost:8082
    prod-url: http://ecole-it.com:8080

server:
  port: 8082