
### Get Post by ID
GET http://localhost:8082/api/posts/1
Authorization: Bearer {your_jwt_token}
###

### Update Post
PUT http://localhost:8082/api/posts/1
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "id": 0,
  "profileId": 0,
  "title": "string",
  "content": "string",
  "creationDate": "2024-01-07T12:51:28.096Z"
}
###

### Delete Post
DELETE http://localhost:8082/api/posts/1
Authorization: Bearer {your_jwt_token}
###

### Get All Posts
GET http://localhost:8082/api/posts
Authorization: Bearer {your_jwt_token}
###

### Create Post
POST http://localhost:8082/api/posts
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "profileId": 1,
  "title": "string",
  "content": "string",
  "creationDate": "2024-01-07T12:51:28.096Z"
}
###

### Get PostLike by ID
GET http://localhost:8082/api/postLikes/1
Authorization: Bearer {your_jwt_token}
###

### Update PostLike
PUT http://localhost:8082/api/postLikes/1
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "postId": 0,
  "profileId": 0
}
###

### Delete PostLike
DELETE http://localhost:8082/api/postLikes/1
Authorization: Bearer {your_jwt_token}
###

### Get All PostLikes
GET http://localhost:8082/api/postLikes
Authorization: Bearer {your_jwt_token}
###

### Create PostLike
POST http://localhost:8082/api/postLikes
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "postId": 1,
  "profileId": 1
}
###

### Get Comment by ID
GET http://localhost:8082/api/comments/{id}
Authorization: Bearer {your_jwt_token}
###

### Update Comment
PUT http://localhost:8082/api/comments/{id}
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "id": 0,
  "profileId": 0,
  "content": "string",
  "creationDate": "2024-01-07T13:08:19.909Z",
  "parentCommentId": 0,
  "postId": 0
}
###

### Delete Comment
DELETE http://localhost:8082/api/comments/{id}
Authorization: Bearer {your_jwt_token}
###

### Get All Comments
GET http://localhost:8082/api/comments
Authorization: Bearer {your_jwt_token}
###

### Create Comment
POST http://localhost:8082/api/comments
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "profileId": 1,
  "content": "second comment",
  "creationDate": "2024-01-07T13:08:19.909Z",
  "parentCommentId": 1,
  "postId": 1
}
###

### Get CommentLike by ID
GET http://localhost:8082/api/commentLikes/{id}
Authorization: Bearer {your_jwt_token}
###

### Update CommentLike
PUT http://localhost:8082/api/commentLikes/{id}
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "commentId": 0,
  "profileId": 0
}
###

### Delete CommentLike
DELETE http://localhost:8082/api/commentLikes/{id}
Authorization: Bearer {your_jwt_token}
###

### Get All CommentLikes
GET http://localhost:8082/api/commentLikes
Authorization: Bearer {your_jwt_token}
###

### Create CommentLike
POST http://localhost:8082/api/commentLikes
Authorization: Bearer {your_jwt_token}
Content-Type: application/json

{
  "commentId": 1,
  "profileId": 1
}
