# application.yml (or application.properties)
spring:
  application:
    name: profile-service


  datasource:
    url: jdbc:postgresql://profile-db/profiles?createDatabaseIfNotExist=true
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

user:
  openapi:
    dev-url: http://localhost:8081
    prod-url: http://ecole-it.com:8080

server:
  port: 8081